### ISSUE TITLE
 Failed to find data adapter that can handle input: <class 'dataloader.DataGenerator'>, <class 'NoneType'>

### ISSUE THREAD

**Issue by VNFace** [dangvansam98/phobert-text-classification#3]
Cho mình hỏi chạy đến đoạn model.fit_generator nó bị lỗi này thì fix như thế nào vậy?
=================================================================
Total params: 518,962
Trainable params: 518,962
Non-trainable params: 0
_________________________________________________________________
None
train_classifer_keras.py:116: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  model.fit_generator(train_generator, epochs=10, verbose=1, validation_data=valid_generator)
Traceback (most recent call last):
  File "train_classifer_keras.py", line 116, in <module>
    model.fit_generator(train_generator, epochs=10, verbose=1, validation_data=valid_generator)
  File "C:\Python37\lib\site-packages\keras\engine\training.py", line 2030, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Python37\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Python37\lib\site-packages\keras\engine\data_adapter.py", line 991, in select_data_adapter
    _type_name(x), _type_name(y)))
ValueError: Failed to find data adapter that can handle input: <class 'dataloader.DataGenerator'>, <class 'NoneType'>

**Comment by HoaNguyen55** [comment]
Hi , please help to fix this issue ASAP. @dangvansam98
